{{- if .Values.log.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "meiwu.name" . }}-filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: log
        enabled: true
        tail_files: true
        fields:
          ip: '${POD_IP}'
        paths:
          - /logs/*.log
        json.keys_under_root: true
        json.overwrite_keys: true
    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    setup.ilm.enabled: false
    setup.template:
      name: "{{ include "meiwu.name" . }}"
      pattern: "{{ include "meiwu.name" . }}-*"
      overwrite: true
    processors:
      - add_cloud_metadata:
    output.elasticsearch:
      username: {{ .Values.log.elasticsearch.username | quote }}
      password: {{ .Values.log.elasticsearch.password | quote }}
      hosts: ['${ELASTICSEARCH_HOST:172.17.48.2}:${ELASTICSEARCH_PORT:9200}']
      index: "{{ include "meiwu.name" . }}-%{+yyyy.MM}"
{{- end }}